deploy_production:
  stage: deploy
  before_script:
   - apt-get update -y && apt-get install sshpass
  script:
  - sshpass -p "${SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no mrk-admin@hybrit-lnv-1
  - cd /robot-status-webapp && git pull && ./docker.sh
  only:
  - master