stages:
- deploy
variables:
  SSH_HOST: mrk-admin@hybrit-lnv-1
  SSH_DOCUMENT_ROOT: /robot-status-webapp
  stage: deploy
   before_script:
   - apt-get update -y && apt-get install sshpass
  script:
  - sshpass -p "${SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no ${SSH_HOST}
  - "cd $SSH_DOCUMENT_ROOT && git pull && ./docker.sh"