deploy_production:
  stage: deploy
  image: ubuntu:16.04
  before_script:
   - apt-get update -qq && apt-get install -y -qq sshpass
  script:
  - sshpass -p "${SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no mrk-admin@hybrit-lnv-1 "cd component-dashboard && git pull https://mrk40:${MRK_PASS}@mrk40.dfki.de/mrk-4.0/component-dashboard.git && ./docker.sh"
  only:
  - master
