deploy_production:
  stage: deploy
  image: ubuntu:16.04
  before_script:
   - apt-get update -qq && apt-get install -y -qq sshpass
  script:
  - sshpass -p "${SERVER_PASS}" ssh -o StrictHostKeyChecking=no -o PreferredAuthentications=password -o PubkeyAuthentication=no mrk-admin@hybrit-lnv-1
  - ls
  - ./update_webapp.sh
  only:
  - master